### ISSUE TITLE
odd behavior for adduct assignment

### ISSUE THREAD

**Issue by cbroeckl** [blosloos/nontarget#11]
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
package.version('nontarget')
[1] "2.2"

I am seeing some odd behavior on the adduct assignment.  

peaklist[c(286:293),]
        mass intensity      rt
286 516.3039      4313 219.702
287 460.2835     10146 220.151
288 478.3128     51264 220.151
289 481.2636     11280 220.151
290 459.2809     39571 220.392
291 476.3074    580096 220.392
292 477.3108    117111 220.392
293 140.0690     29229 221.280

this appears to be a single monomer of a PEG polymer, and it is apparently an ammonium and protonated adduct (we are using an ammonium buffer here).  You can see that peaks 290 and 291 differ by the mass of an NH4 (approximately).   If i fragment the M+NH4 ion i see 459, as i have seen from other analytes.  I am using this as a test case, there are other PEG monomers showing the same trend.  

The problem is that i can not see ANY ammonium adducts reported in the results.  
ads <- adduct.search(peaklist, adducts[which(adducts$Charge > 0),], mztol = 150)
 
(doesn't matter what mztol i use, it seems )

the peaks 290 and 291 are not assigned to any adduct group.   In fact, there is not a single ammonium adduct recognized in the whole dataset, even though i can pretty easily manually find 8-10 looking at the raw data.   FWIW, the isotope assignment does seem to work, as 477 and 478 ions are assigned to 476, with isotope possibilities which include 15N.

I am a new user - anything i am doing wrong?

**Comment by blosloos** [comment]
Hi Corey

Does increasing the parameter `rttol > 0` in `adduct.search()` change anything? Maybe the rt values in your peaklist are rounded?

**Comment by cbroeckl** [comment]
@blosloos - rttol  has no impact.  To be clear, it is detecting M+H, M+Na, and M+K relationships, just not M+NH4.

**Comment by cbroeckl** [comment]
@blosloos - user error.  i thought the adduct table was the instruction for which adducts to consider, and failed to (re)set the use.adducts option to inlcude ammonium.   i will close this issue with this comment.

**Comment by blosloos** [comment]
:-)

**Comment by cbroeckl** [comment]
indeed - easiest problems to fix aren't they ;-)

**Comment by blosloos** [comment]
totally! its sometimes just best to wait a while for problems to fix themselves :-)
