### ISSUE TITLE
How to fix Error: Maximum number of tupels reached. increase vec_size?

### ISSUE THREAD

**Issue by makhashmi** [blosloos/nontarget#4]
I was trying to run Nontarget Package R for homologus series from Mass spectroscopy data.  R script runs but when it reaches to 46% it gives following error 
`"Maximum number of tupels reached. increase vec_size".  `
However, when I try to increase vec_size then R script gives error of

```
" invalid 'nrow' value (too large or NA)
In addition: Warning message:
In matrix(nrow = vec_size, ncol = 7, 0) :
  NAs introduced by coercion to integer range".  
```

The code I am using is given below,

> homol=NULL
> mzfil=c(14.0157, 30.0106, 44.0262, 58.0419, 74.0188, 49.9968, 7.0079, 15.0053, 22.0131, 29.0210, 37.0094, 24.9984)
> homol<-homol.search(sample_NA, isotopes, elements=c("C","H","O","Si","F"), 
>                    use_C=TRUE, minmz=7, maxmz=80, minrt=0.0, maxrt=3, ppm=TRUE, 
>                    mztol=2.5, rttol=0.2, minlength=4, R2=.96, spar=0.5, plotit=FALSE, mzfilter=mzfil, vec_size = 3E9)
> path=file.path("S:\\4_Cluster_Analysis_01Nov18thu\\1_step1_JDS_Cleaning\\1_JDS3_ESIpos\\JDS_08_Oberloiben\\Output_Homol_plot_ESIpos_JDS_08.jpeg")
> jpeg(file=path, width = 2000, height = 2000, units = "px", pointsize = 20, res=re)
> 

Would it be possible for you to figure out how it can be fixed? 
Thank you!

**Comment by blosloos** [comment]
dear makhashmi - tanks for your interest in the nontarget package.

internally, homol.search needs to store findings from the triplet search in a matrix. depending on the data set, the default matrix (n.rows = 3E6) for doing so may be too small. depending on y our computers RAM, 1E9 on the other hand may be too large. try sth in between.

if that does not help, please also try reverting to an earlier version of R (preferably v 3.3.3). there have been issues reported with the latest version of R and nontarget - but no time to fix them yet ....

**Comment by makhashmi** [comment]
dear blosloos,

Thanks for your reply.

it worked as you mentioned after increaseing vec_size = 1E7.

now after homologus series, I wanted to combine the data but code keeps running with the message of:

```
done.
 (1) Assemble lists...
 (2) Combine...
```

and seems to never end unless one has to interrupt it by clicking on stop.  and when I stop it, it gives the error like "`There were 50 or more warnings (use warnings() to see the first 50)`" and warnings message is "`1: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL`'".

is it possible to fix this? 

The code which gives this eror is given below:
```
comp=combine(pattern, adduct, homol, rules=c(TRUE, FALSE, FALSE), dont=FALSE)
write.csv(comp$Components, "S:\\4_Cluster_Analysis_01Nov18thu\\1_step1_JDS_Cleaning\\1_JDS3_ESIpos\\JDS_08_Oberloiben\\comp_ESIpos_JDS_08.csv")

comp_only=combine(pattern, adduct, homol, rules=c(TRUE, TRUE, FALSE), dont=FALSE) #keeps only comp. with more than two peaks 
write.csv(comp_only$Components, "S:\\4_Cluster_Analysis_01Nov18thu\\1_step1_JDS_Cleaning\\1_JDS3_ESIpos\\JDS_08_Oberloiben\\comp_only_ESIpos_JDS_08.csv")
```

**Comment by blosloos** [comment]
have you tried this on an earlier R version 3.3.3? same error?

**Comment by makhashmi** [comment]
yes, I installed version 3.3.3 and ran script but it gives the same error.

**Comment by tsufz** [comment]
Hi Martin,
Yes, we have also the same problem. We tried with 3.3.3, but it may be related to another updated package. 

`SessionInfo()`
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.3

Yours
Tobias

**Comment by tsufz** [comment]
Hi Martin,
We face the same problem. The output of `SessionInfo()` (with loaded nontarget):

> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nontarget_1.9     mgcv_1.8-17       nlme_3.1-131      nontargetData_1.1 enviPat_2.2      

loaded via a namespace (and not attached):
[1] Matrix_1.2-8    tools_3.3.3     grid_3.3.3      lattice_0.20-34

Yours,
Tobias

**Comment by blosloos** [comment]
Hi Tobias. Would you mind sending me the concerned peaklist for checking? I will delete it afterwards, promised. Will send you an email now, so you have my address ...

**Comment by blosloos** [comment]
... sorry for the delay. You have a lot of peaks which interfere with each other (= false positive relations) during the componentization, apart from a smaller non-hazardous bug which gave the warning message during for combine(...). Thus, the calculation in this old-coded package takes ages. Am trying to fix the problem by Monday latest with an option to deal with those interfering peaks during the componentization and make the package available on github.

**Comment by tsufz** [comment]
Hi Martin, no problem. Great that you identified the problem. We are looking forward to the updated version.

Have a nice weekend
Tobias

**Comment by blosloos** [comment]
...as mentioned, there is plenty of co-elution of peaks in the beginning of the RT range (elution dead volume?), which makes the combine(...)-function extremely slow and the resulting components meaninglessly overcrowded. As a brute force approach for such a setting, combine(...) now has another rule added, please check its help file. Namely, rule[1] omits interfering peaks from entering the componentization, while former rules[1] to [3] are now represented by rules [2] to [4]. @Tobias, your peaklist now runs through, with adapting to 

```
comp <- combine(
	pattern, 
	adduct, 
	homol, 
	rules = c(FALSE, TRUE, FALSE, FALSE), 
	dont = FALSE
)
```
For the time being, you will have to install the adapted package from GitHub, instead of R CRAN. To do so, download Rtools and the CRAN devtools package for R 3.3.3 and run

```
library(devtools)
install_github(repo = "blosloos/nontarget")
```

**Comment by makhashmi** [comment]
Hi there,

Yes it worked out.  Thanks for solving the issue...............
