### ISSUE TITLE
problem with homol.search code

### ISSUE THREAD

**Issue by ldag27** [blosloos/nontarget#5]
There is a condition in the function homol.search:
if(!is.numeric(mzfilter) & mzfilter[1]!="FALSE"){stop("mzfilter must either be a numeric vector or set to FALSE")}
The quotes around FALSE do not allow it to functions if mzfilter = FALSE. They should be removed.

**Comment by blosloos** [comment]
What does

mzfilter <- "FALSE"
!is.numeric(mzfilter) & (mzfilter[1] == "FALSE")

return in your R version? And what is the return value of

mzfilter <- FALSE
!is.numeric(mzfilter) & (mzfilter[1] == "FALSE")

At least in my outdated R v3.3.3 the output is the same.

**Comment by ldag27** [comment]
Those do give the same results, but with the first one mzfilter is a character and with the second one mzfilter is a logical.

**Comment by blosloos** [comment]
I do not understand what the issue is here? Please clarify
