### ISSUE TITLE
Workarounds for homol.search() with R>3.3.3

### ISSUE THREAD

**Issue by rickhelmus** [blosloos/nontarget#6]
Hello,

Currently `homol.search()` gives all kind of funny errors with R 3.5. One that always appears on a first run is
```
in `[<-`(`*tmp*`, 1, 1, value = (peaklist2[use, 1] + minmz)) : 
  subscript out of bounds
```

Subsequent calls then result in
```
Error in if (!is.numeric(mzfilter) & mzfilter[1] != "FALSE") { : 
  missing value where TRUE/FALSE needed
```

I spent some time debugging (with `trace()` or putting some `browser()` calls in the source) and both error messages are simply wrong and something else is going on... As R seems to be internally confused I can imagine it might be something related with the C code, but I haven't been able to pin point where. I started commenting out random code blocks in various C functions, but as they are all highly dependent on each other this is not really working out.

What is interesting is that calling `trace(homol.search, edit = TRUE)` and putting a `browser()` call *somewhere* makes any error disappear! In fact, one ugly workaround would be to do...
```R
trace(nontarget::homol.search, function() {}) # put in dummy trace
homol.search(...) # do the thing...
untrace(nontarget::homol.search)
```

I noticed that putting in a trace actually disables byte compiling (a feature that is now enabled by default on R 3.5). Hence, I tried to disable byte compiling in the package DESCRIPTION by adding
```
ByteCompile: FALSE
```
This works, but only once. It seems on a second call R stubbornly still byte compiles the function. This can be prevented by disabling the JIT completely by calling `compiler::enableJIT(0)`.

I think for now I will stick with the first workaround as it seems least pervasive. Martin, if you have any ideas or you think I can further help with debugging please let me know!

Thanks,
Rick

**Comment by blosloos** [comment]
Please use this package with R version 3.3.3 or lower. A working update of the package will either be made available in 2019 or the package will be orphaned and its functions embedded directly in enviMass. The problem you observe likely arises from changes in the C interfacing.

**Comment by rickhelmus** [comment]
Hello,

This comment wasn't meant to say otherwise, apologies if I caused any confusion! My comment was mainly meant to summarize a few workarounds for users that do want to use `nontarget` with a newer R version (even when it is **not** supported).

It would be really great when `nontarget` continues to support newer R versions :-)

**Comment by blosloos** [comment]
thanks! I will take your input into account when working on the next update!

**Comment by rickhelmus** [comment]
Great! Seems to be the right time to me to close the issue then .. :-)
